### ISSUE TITLE
Update for marshmallow

### ISSUE THREAD

**Issue by mark-e-mark** [ztc1997/VibrationTuner#1]
This is a request for an update for MM. Notification "It seems the module is not activated properly."  I'd be happy to donate in support of the app.

**Comment by unexpectedkas** [comment]
I agree. A quick search in google shows how many people looking forward for this to work.

**Comment by ghost** [comment]
GravityBox has implemented vibration control: https://github.com/GravityBox/GravityBox/commit/6cd592c56022a1b30bdaca6482848027fbe9c91e

The feature is behind a paywall (any donation amount) and I haven't been able to get it working, though.

**Comment by ghost** [comment]
The developer is working on the issue: https://github.com/ztc1997/VibrationTuner/commits?author=ztc1997

**Comment by ztc1997** [comment]
dca102656e401cfae050b721503609f3a6e19919  This module has been compatible with Marshmallow.

**Comment by mark-e-mark** [comment]
Thank you! The latest version has not appeared Xposed repo yet.

**Comment by reddit-is-fun** [comment]
@ Hopefully it will soon, I have never compiled Android apps from source.

**Comment by ztc1997** [comment]
@reddit-is-fun @mark-e-mark The apk of new version(1.0.1) has been upload to xposed repo as soon as I committed it. check here http://repo.xposed.info/module/ztc1997.vibrationtuner

**Comment by mark-e-mark** [comment]
Downloaded and enabled via Xposed. It's working! The Virtual key Vibration
strength set to almost max makes the key press confident now. Thank you!

**Comment by ghost** [comment]
Lovely, after taking a quick test drive works flawlessly.
